### ISSUE TITLE
Remove "Enable xml-formatter" from right-click menu

### ISSUE THREAD

**Issue by kankaristo** [neyestrabelli/xml-formatter#17]
Thanks for a great package! I work with a lot of XML files, and this is very useful to have.

However, one thing is annoying me a bit. The "Enable xml-formatter" item is **always** in the right-click menu, even if you're not in an XML file (it's there in the tree view, the settings view, etc).

It should only be there in XML files. IMO, it shouldn't be there at all, because that's what the command palette is for. :)

**Comment by kankaristo** [comment]
I found [this](https://discuss.atom.io/t/how-to-remove-items-from-menus-of-existing-packages/16329/9), so I can remove the context menu item manually.

I still think that the context menu item should only be visible in XML files. No other package (out of the ~100 I have installed) adds a context menu item in the tree-view, etc.

**Comment by vith** [comment]
This still shows up when right clicking non-XML files.

https://discuss.atom.io/t/context-sensitive-context-menu/19573/2 has some hints on how to make the menu entry's visibility selective.
