### ISSUE TITLE
When the xml file starts with a byte-order-mark, a duplicate xml header is created when formatting the text

### ISSUE THREAD

**Issue by dander** [neyestrabelli/xml-formatter#18]
for example,

    ﻿<?xml version="1.0" encoding="UTF-8"?><foo></foo>

becomes

    <?xml version="1.0" encoding="UTF-8"?>
    <?xml version="1.0" encoding="UTF-8"?>
    <foo>
    </foo>

This only occurs when the "XML UTF8 header" setting is enabled

**Comment by neyestrabelli** [comment]
@dander thanks for your feedback.

Check the new version: 0.9.1 -  078428707e4c17130ff3f362c2dc0a7facb0415a

**Comment by dander** [comment]
Thanks! I've verified this issue is fixed in that version.
