### ISSUE TITLE
Option to not reorder noder attributes.

### ISSUE THREAD

**Issue by BitBrit** [neyestrabelli/xml-formatter#25]
At the moment the plugin will reorder this:
``
<xs:element name="bs46" type="subscriber:BS46" minOccurs="0" maxOccurs="unbounded"/>
``
To this:
``
<xs:element maxOccurs="unbounded" minOccurs="0" name="bs46" type="subscriber:BS46"/>
``
This makes the XML a lot harder to visually inspect as it puts (in this case) the most pertinent element (which is the 'name' attribute) in the middle of the XML node attribute list.  

Could there be an option in settings to not reorder the attributes and instead only correctly indent the XML file?

Really nice plugin btw. I use it a lot.

**Comment by neyestrabelli** [comment]
Hi @BitBrit , the plugin don't reorder a xml.

I copied your code but works fine.
