### ISSUE TITLE
Atom - "Editor is not responding" when attempting to format

### ISSUE THREAD

**Issue by TheFoggyRoad** [neyestrabelli/xml-formatter#27]
When I attempt to format a 5MB XML file, Atom stops responding. I just installed this package today and am using Shift + Ctrl + X. Please let me know what I can do to assist in troubleshooting.

Windows 10 x64
Atom 1.5.4

**Comment by neyestrabelli** [comment]
Hi, I work with files with  > 10mb and works fine.
