### ISSUE TITLE
xml-formatter ignores encoding attribute specified in XML declaration

### ISSUE THREAD

**Issue by kowalcj0** [neyestrabelli/xml-formatter#28]
For example when you indent this example XML: 
```xml
<?xml version="1.0" encoding="Windows-1252"?><service></service>
```

you'll end-up with a **UTF-8** document 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<service>
</service>
```
Surely this is not the same file as the original one :)

ps. I think this is partially related to a closed issue #14 

Cheers

**Comment by neyestrabelli** [comment]
Hi @kowalcj0 you can disable UTF-8 header in settings.
