### ISSUE TITLE
Feature Request: Reverse functionality

### ISSUE THREAD

**Issue by Aaron-Acox** [neyestrabelli/xml-formatter#30]
Please add a minify function that removes linebreaks and whitespace between tags.  Thanks.

**Comment by aleclarson** [comment]
I want this, too. 😁

**Comment by neyestrabelli** [comment]
@Aaron-Acox @aleclarson nice request, any suggestion for a shortcut or just add on menu?

**Comment by aleclarson** [comment]
I would use it thru the Command Palette (cmd+shift+P)

**Comment by neyestrabelli** [comment]
Ok, check new version 0.11.0 :)
