### ISSUE TITLE
Not showing up in Packages menu

### ISSUE THREAD

**Issue by CTAdam** [neyestrabelli/xml-formatter#33]
After installing and ensuring enabled, xml-formatter is not visible in Menu.

**Comment by neyestrabelli** [comment]
Try to restart atom or check if you have the version 0.12.0, because here it's working normally.

![captura de tela 2019-01-24 as 08 45 50](https://user-images.githubusercontent.com/784107/51673214-95d74c00-1fb4-11e9-8fb2-86543fc7ef3d.jpg)

**Comment by CTAdam** [comment]
It was actually right after the update that it disappeared. 

![image](https://user-images.githubusercontent.com/5864170/51691476-d6d95b80-1fc8-11e9-89de-418ec80064a2.png)

**Comment by neyestrabelli** [comment]
@CTAdam packages menu is fixed on version 0.13.0, please check if works.

**Comment by ghost** [comment]
@neyestrabelli Fixed. Great. Thank you.
